version: v2beta1
name: ark-filesystem

# Define images to build
images:
  file-api:
    image: file-api
    dockerfile: ./services/file-api/Dockerfile
    context: ./services/file-api
    buildKit:
      preferMinikube: true
    tags:
      - latest

  # filesystem-mcp:
  #   image: filesystem-mcp-server
  #   dockerfile: ./services/filesystem-mcp/Dockerfile
  #   context: ./services/filesystem-mcp
  #   rebuildStrategy: ignoreContextChanges

# Deploy using your Helm chart
deployments:
  ark-filesystem:
    helm:
      chart:
        name: ./chart
      values:
        # Override image tags to use devspace-built images
        fileApi:
          image:
            repository: ${runtime.images.file-api.image}
            tag: ${runtime.images.file-api.tag}
            pullPolicy: Never

        # filesystem-mcp uses external image for now
        filesystemMcp:
          enabled: true
          image:
            repository: ghcr.io/mckinsey/agents-at-scale-ark/filesystem-mcp-server
            tag: latest
            pullPolicy: IfNotPresent

        # versitygw uses public image
        versitygw:
          enabled: true
          image:
            repository: ghcr.io/versity/versitygw
            tag: latest
            pullPolicy: IfNotPresent
          createSecret: true
          s3Credentials:
            accessKeyId: "devspace-admin"
            secretAccessKey: "devspace-secret-key-change-me"

        # Storage configuration
        storage:
          enabled: true
          size: 1Gi
          storageClassName: ""

# Development configuration
dev:
  file-api:
    imageSelector: file-api
    ports:
      - port: "8080:8080"
    sync:
      - path: ./services/file-api/src:/app/src
        printLogs: true
    command: ["python", "-m", "file_api"]

  filesystem-mcp:
    labelSelector:
      app.kubernetes.io/component: filesystem-mcp
    ports:
      - port: "8000:8000"

  versitygw:
    labelSelector:
      app.kubernetes.io/component: versitygw
    ports:
      - port: "7070:7070"

# Pipelines for common tasks
pipelines:
  dev:
    run: |-
      run_dependencies --all
      build_images --all
      create_deployments --all
      start_dev --all

  deploy:
    run: |-
      build_images --all
      create_deployments --all
