# DevSpace configuration for MCP Inspector
version: v2beta1

pipelines:
  dev: |-
    create_deployments --all

deployments:
  mcp-inspector:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        httpRoute:
          enabled: true

hooks:
  - command: |-
      echo ""
      echo "Dashboard URL:"
      echo "  http://mcp-inspector.default.127.0.0.1.nip.io:8080/?MCP_PROXY_FULL_ADDRESS=http://mcp-inspector-proxy.default.127.0.0.1.nip.io:8080"
      echo ""
      echo "Port forward:  kubectl port-forward svc/mcp-inspector 6274:6274"
      echo ""
      echo "Usage:"
      echo "  1. Go to Configuration and set Proxy Session Token to 'test'"
      echo "  2. Connect to an MCP server: kubectl get mcpserver -A"
    events: ["after:deploy:mcp-inspector"]
