apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lx-adverse-media-screening-
spec:
  workflowTemplateRef:
    name: lx-adverse-media-screening
  arguments:
    parameters:
      - name: execution-mode
        value: "sequential"
