apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lx-initial-risk-assessment-
  namespace: default
spec:
  workflowTemplateRef:
    name: lx-initial-risk-assessment
  arguments:
    parameters:
      - name: intermediate-dir
        value: "source_code_files/1-customer-profile-initialization/intermediate"
      - name: output-dir
        value: "source_code_files/1-customer-profile-initialization/output"
