apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lx-profile-enrichment-
  namespace: default
spec:
  workflowTemplateRef:
    name: lx-profile-enrichment
  arguments:
    parameters:
      - name: execution-mode
        value: "sequential"
      - name: company-name
        value: "ASSOCIATED BRITISH FOODS PLC"
      - name: company-number
        value: "00293262"
      - name: web-prompts-file
        value: "source_code_files/1-customer-profile-initialization/input/prompts_web_data.yml"
      - name: gov-prompts-file
        value: "source_code_files/1-customer-profile-initialization/input/prompts_uk_gov.yml"
      - name: output-dir
        value: "source_code_files/1-customer-profile-initialization/intermediate"
