apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lx-retrieve-entities-vessels-
spec:
  workflowTemplateRef:
    name: lx-retrieve-entities-vessels
  arguments:
    parameters:
      - name: execution-mode
        value: "sequential"
