{{- if .Values.modelProvider.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.modelProvider.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}-model-provider
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
