# DevSpace configuration for A2A Inspector
version: v2beta1

pipelines:
  dev: |-
    create_deployments --all

deployments:
  a2a-inspector:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        httpRoute:
          enabled: true

hooks:
  - command: |-
      echo ""
      echo "A2A Inspector: http://a2a-inspector.default.127.0.0.1.nip.io:8080"
      echo "Port forward:  kubectl port-forward svc/a2a-inspector 8080:8080"
      echo ""
      echo "Usage:"
      echo "  1. Connect to an A2A agent by entering its URL"
      echo "  2. View the agent card and perform spec compliance checks"
    events: ["after:deploy:a2a-inspector"]
