version: v2beta1

pipelines:
  deploy: |-
    create_deployments --all
  dev: |-
    create_deployments --all

deployments:
  cobol-modernization-bundle:
    namespace: cobol-demo
    helm:
      chart:
        path: chart
      values: {}
