apiVersion: v2
name: phoenix
description: Phoenix observability with OTEL configuration
type: application
version: 0.1.7
appVersion: 4.0.5
annotations:
  ark.mckinsey.com/service: phoenix
  ark.mckinsey.com/resources: service
dependencies:
  - name: ark-marketplace-common
    version: "0.1.0"
    repository: "oci://ghcr.io/mckinsey/agents-at-scale-marketplace/charts"
  - name: phoenix-helm
    version: 4.0.5
    repository: oci://registry-1.docker.io/arizephoenix
