# DevSpace configuration for langchain-executor
version: v2beta1

images:
  langchain-executor:
    image: langchain-executor
    dockerfile: Dockerfile
    context: .

pipelines:
  deploy: |-
    build_images --all
    create_deployments --all
  dev: |-
    create_deployments --all
    start_dev --all

deployments:
  langchain-executor:
    namespace: default
    helm:
      chart:
        path: ./chart
      values:
        image:
          repository: ${runtime.images.langchain-executor.image}
          tag: ${runtime.images.langchain-executor.tag}
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
            ephemeral-storage: 100Mi

dev:
  langchain-executor:
    imageSelector: langchain-executor
    devImage: python:3.12-slim
    command:
      [
        "sh",
        "-c",
        "cd /app && pip install uv && uv sync && uv run python -m langchain_executor",
      ]
    namespace: default
    logs:
      lastLines: 50
    sync:
      - path: .:/app
        startContainer: true
        disableDownload: true
        uploadExcludeFile: .dockerignore
    ssh:
      enabled: true
