apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: kyc-onboarding-template
  annotations:
    workflows.argoproj.io/title: "KYC Customer Onboarding"
    workflows.argoproj.io/description: "Complete KYC customer onboarding workflow with document verification, risk assessment, and compliance reporting"
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: customer-data-file
        value: "customers/john-doe.txt"
      - name: output-report-file
        value: "reports/john-doe-kyc-report.md"
  templates:
    - name: main
      steps:
        - - name: full-kyc-verification
            template: query-kyc-team
            arguments:
              parameters:
                - name: customer-data-file
                  value: "{{workflow.parameters.customer-data-file}}"
                - name: output-report-file
                  value: "{{workflow.parameters.output-report-file}}"
        - - name: process-results
            template: process-kyc-results
            arguments:
              parameters:
                - name: kyc-report
                  value: "{{steps.full-kyc-verification.outputs.parameters.response}}"
                - name: output-report-file
                  value: "{{workflow.parameters.output-report-file}}"

    - name: query-kyc-team
      inputs:
        parameters:
          - name: customer-data-file
          - name: output-report-file
      script:
        image: alpine/k8s:1.28.13
        command: [sh]
        source: |
          set -eux

          QUERY_NAME="kyc-{{workflow.name}}-$(date +%s%N)"

          cat <<'EOF' | sed "s/QUERY_NAME/$QUERY_NAME/" | kubectl apply -n default -f -
          apiVersion: ark.mckinsey.com/v1alpha1
          kind: Query
          metadata:
            name: QUERY_NAME
            labels:
              workflow: "{{workflow.name}}"
              use-case: kyc-onboarding
          spec:
            input: |
              New customer onboarding request:

              IMPORTANT: Read the customer data from the file: {{inputs.parameters.customer-data-file}}

              The file contains complete customer information including:
              - Personal information (name, DOB, nationality, address, contact)
              - Identification documents (passport, driver's license)
              - Business profile (purpose, expected transactions, source of funds, employment details)

              Instructions:
              1. Use the read_file tool to read the customer data from {{inputs.parameters.customer-data-file}}
              2. Perform complete KYC verification based on the data in the file
              3. Generate a comprehensive compliance report
              4. Use the write_file tool to save the final compliance report to: {{inputs.parameters.output-report-file}}

              Please perform complete KYC verification and provide onboarding recommendation.
            target:
              type: team
              name: kyc-verification-team
            timeout: 5m
            ttl: 24h
          EOF

          kubectl wait --for=condition=Completed --timeout=5m -n default query/$QUERY_NAME || true

          kubectl get query $QUERY_NAME -n default -o json > /tmp/query.json
          PHASE=$(jq -r '.status.phase' /tmp/query.json)

          if [ "$PHASE" = "error" ]; then
            ERROR_MESSAGE=$(jq -r '.status.responses[0].content // .status.error // "Unknown error"' /tmp/query.json)
            echo "$ERROR_MESSAGE"
            exit 1
          fi

          jq -r '.status.responses[0].content // ""' /tmp/query.json | tee /tmp/response.txt
      outputs:
        parameters:
          - name: response
            valueFrom:
              path: /tmp/response.txt

    - name: process-kyc-results
      inputs:
        parameters:
          - name: kyc-report
          - name: output-report-file
      script:
        image: alpine:3.19
        command: [sh]
        source: |
          set -e

          echo "================================================================================"
          echo "KYC ONBOARDING WORKFLOW COMPLETE"
          echo "================================================================================"
          echo "Workflow: {{workflow.name}}"
          echo "Completed: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          echo ""
          echo "================================================================================"
          echo "SUMMARY"
          echo "================================================================================"
          echo ""
          echo "The KYC verification team has completed the customer onboarding process."
          echo ""
          echo "Report saved to: {{inputs.parameters.output-report-file}}"
          echo ""
          echo "You can access the full compliance report using the file-gateway or"
          echo "by querying the file-gateway MCP server."
          echo ""
          echo "================================================================================"
          echo "WORKFLOW RESPONSE"
          echo "================================================================================"
          echo ""
          echo "{{inputs.parameters.kyc-report}}"
          echo ""
          echo "================================================================================"
          echo "END OF WORKFLOW"
          echo "================================================================================"
