{{- if .Values.auth.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argo-workflow-runner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.key }}: "Bearer {{ .Values.auth.token }}"
{{- end }}
