{{- if .Values.scheduler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-scheduler
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}-scheduler
  annotations:
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}-scheduler
{{- end }}
