apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web-research-mcp.fullname" . }}-sa
  labels:
    {{- include "web-research-mcp.labels" . | nindent 4 }}
automountServiceAccountToken: false
