apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "perplexity-ask-mcp.fullname" . }}-sa
  labels:
    {{- include "perplexity-ask-mcp.labels" . | nindent 4 }}
automountServiceAccountToken: false
