# DevSpace configuration for Phoenix observability
version: v2beta1

vars:
  HTTPROUTE_ENABLED:
    command: |-
      if kubectl get crd httproutes.gateway.networking.k8s.io >/dev/null 2>&1; then
        echo "true"
      else
        echo "false"
      fi

pipelines:
  dev: |-
    create_deployments --all

deployments:
  phoenix:
    namespace: phoenix
    helm:
      chart:
        path: ./chart
      values:
        # Development-specific values can be added here
        httpRoute:
          # when true, http://phoenix-svc.phoenix.127.0.0.1.nip.io:8080 will be created
          enabled: ${HTTPROUTE_ENABLED}
        otelEnvironmentVariableSecrets:
          enabled: true
          namespaces:
            - ark-system
            - default

hooks:
  - command: |-
      # Check if Gateway API HTTPRoute CRD exists
      if kubectl get crd httproutes.gateway.networking.k8s.io >/dev/null 2>&1; then
        echo "✓ Gateway API HTTPRoute CRD found - HTTPRoute will be created"
      else
        echo "✗ Gateway API HTTPRoute CRD not found - HTTPRoute will be skipped"
      fi
    events: ["before:deploy:phoenix"]
  - command: |-
      echo "Restarting ark-controller to pick up Phoenix configuration..."
      
      # Check if ark-controller-devspace exists first (DevSpace deployment)
      if kubectl get deployment ark-controller-devspace -n ark-system >/dev/null 2>&1; then
        echo "Found ark-controller-devspace, restarting..."
        kubectl rollout restart deployment/ark-controller-devspace -n ark-system
        kubectl rollout status deployment/ark-controller-devspace -n ark-system --timeout=120s
      # Otherwise check for regular ark-controller deployment
      elif kubectl get deployment ark-controller -n ark-system >/dev/null 2>&1; then
        echo "Found ark-controller, restarting..."
        kubectl rollout restart deployment/ark-controller -n ark-system
        kubectl rollout status deployment/ark-controller -n ark-system --timeout=120s
      else
        echo "Warning: No ark-controller deployment found in ark-system namespace"
      fi
    events: ["after:deploy:phoenix"]
