{{- if .Values.argoWorkflows.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.argoWorkflows.serviceAccountName }}
  labels:
    {{- include "onboarding.labels" . | nindent 4 }}
{{- end }}
