apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "companies-house-mcp.fullname" . }}-sa
  labels:
    {{- include "companies-house-mcp.labels" . | nindent 4 }}
automountServiceAccountToken: false
