apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pdf-extraction-mcp.fullname" . }}-sa
  labels:
    {{- include "pdf-extraction-mcp.labels" . | nindent 4 }}
automountServiceAccountToken: false
